### ISSUE TITLE
Impossible to bundle

### ISSUE THREAD

**Issue by nicalpi** [thoughtbot/geocoding-on-rails#60]
Hi guys, 

I've bought the Geocoding on rails book, but I'm not a prime member (which is I think where the issue lives).

Git clone and running bundle on this repo replies with this error:

```
➜  geocoding-on-rails git:(master) bundle
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/..
Fetching git@github.com:thoughtbot/paperback.git
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Git error: command `git clone 'git@github.com:thoughtbot/paperback.git' "/home/nicolas/.rvm/gems/ruby-1.9.3-p362/cache/bundler/git/paperback-e2ebaac0d48f189cf2999c60ece4fa84ce514406" --bare --no-hardlinks` in directory /home/nicolas/tmp/geocoding-on-rails has failed.
```

**Comment by croaky** [comment]
Hi @spyou,

The Paperback gem is a private repo. We use it at thoughtbot when we're writing the book, but you shouldn't need it when reading the book.

What's your preferred format? You should be able to read [the PDF version](https://github.com/thoughtbot/geocoding-on-rails/raw/master/release/geocoding-on-rails.pdf), [Epub version](https://github.com/thoughtbot/geocoding-on-rails/raw/master/release/geocoding-on-rails.epub), or [Mobi version](https://github.com/thoughtbot/geocoding-on-rails/raw/master/release/geocoding-on-rails.mobi) using the links in this sentence. The HTML version is best viewed from the cloned version you already have on your machine:

```
cd geocoding-on-rails
open release/geocoding-on-rails.html
```

**Comment by nicalpi** [comment]
Damn, my bad, I didn't catch that the repo was for everything. The one I was looking to bundle is geocoding_on_rails/example_app/.

Sorry

**Comment by malandrina** [comment]
@spyou, were you able to resolve this? Does running `bundle` for the example app work for you?

**Comment by jessieay** [comment]
Hi @spyou - If you are trying to use the example app, you can do:

```
cd geocoding-on-rails/example_app
```

Once you are in there, you can bundle like you would with a normal Rails app. The example app does not use the private gem, so you should be good to go.

Closing this issue for now, but definitely comment here or open a new issue if you have problems bundling within the app itself.
